# Notes for STATS102, Session 1, Aug 31th, Lecture
partial materials are from the text book 
Python Data Science Handbook: Essential Tools for Working with Data, by Jake VanderPlas, O'Reilly Media; 1 edition (December 10, 2016), ISBN-13: 978-1491912058, full text and code freely available at https://jakevdp.github.io/PythonDataScienceHandbook/.

# Numpy

In [1]:
import numpy as np
np.__version__


'1.14.0'

# Creating Arrays from Python Lists

In [8]:
# integer array:
a=np.array([1, 4, 2, 5, 3])
b=np.array([3.14, 4, 2, 3,4])
d=np.array([3.14, 4])
c=[1, 4, 2, 5, 3]
type(b[1])

numpy.float64

In [9]:
type (a[0])

numpy.int32

In [10]:
type(b[1])

numpy.float64

In [ ]:
c

In [11]:
type(a[1])

numpy.int32

In [13]:
a

array([1, 4, 2, 5, 3])

In [14]:
b

array([3.14, 4.  , 2.  , 3.  , 4.  ])

In [15]:
a+1

array([2, 5, 3, 6, 4])

In [16]:
type(b[1])

numpy.float64

In [ ]:
b[3]

In [17]:
[        list(range(i, i + 3))          for i in [2,4,6]       ]

[[2, 3, 4], [4, 5, 6], [6, 7, 8]]

In [19]:
[list(range(i,i+3))  for i in [1,4,7]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
mylist=[]
for i in [1,4,7]:
    mylist.append(list(range(i,i+3)))
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
list(range(2,5))

In [21]:
# nested lists result in multi-dimensional arrays
c=np.array([list(range(i, i + 3)) for i in [2, 4, 6]])
c

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
c.T

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [24]:
c=np.array([1, 2, 3, 4], dtype='int16')
type(c[0])

numpy.int16

In [27]:
c[0]=2**15-1
c[0]

32767

In [31]:
c[0]=-2**15
c[0]

-32768

-32768

In [34]:
temp=np.array([range(i, i + 4) for i in [2, 4, 6]])
temp

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [35]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

In [36]:
[list(range(i, i + 3)) for i in [2, 4, 6]]

[[2, 3, 4], [4, 5, 6], [6, 7, 8]]

In [37]:
a=[i*2 for i in [2, 4, 6]]
print(a)

[4, 8, 12]


In [38]:
np.array(a)

array([ 4,  8, 12])

In [39]:
a=[[1,2],[3,4]]
b=np.array(a)
b

array([[1, 2],
       [3, 4]])

# Creating Arrays from Scratch

In [40]:
# Create a length-10 integer array filled with zeros
np.zeros([10,10], dtype='int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Create a 3x5 array filled with 3.14
a=np.full((3, 5), -1.1)
a

array([[-1.1, -1.1, -1.1, -1.1, -1.1],
       [-1.1, -1.1, -1.1, -1.1, -1.1],
       [-1.1, -1.1, -1.1, -1.1, -1.1]])

In [13]:
np.abs(a)

array([[1.1, 1.1, 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, 1.1, 1.1]])

In [14]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.array(range(0,20,2))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
a=np.empty((5,5))
#a.dtype='int32'
a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11262860e-307, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.33511969e-306, 1.86921143e-306],
       [7.56587585e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.33511018e-306],
       [6.23057689e-307, 1.33511562e-306, 6.89805151e-307,
        2.56765117e-312, 2.30908182e+251]])

# NumPy Array Attributes

In [51]:
np.random.seed(10)
np.random.randint(3,6,10)

array([4, 4, 3, 3, 4, 3, 4, 4, 3, 4])

In [54]:

x1 = np.random.randint(3,10, size=6)  # One-dimensional array

print(x1)
x2 = np.random.randint(0,10, size=(3, 4))  # Two-dimensional array
print(x2)
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("dtype:", x2.dtype)


[7 6 9 3 6 5]
[[1 8 4 1]
 [3 6 5 3]
 [9 6 9 1]]
x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
dtype: int32


# Array Indexing and Slicing

In [55]:
print(x1)
x1[1]

[7 6 9 3 6 5]


6

In [56]:
print(x2)

x2[0, 2]


[[1 8 4 1]
 [3 6 5 3]
 [9 6 9 1]]


4

In [57]:
x2[0][2]

4

In [58]:
x2[0, 0] = 12
x2

array([[12,  8,  4,  1],
       [ 3,  6,  5,  3],
       [ 9,  6,  9,  1]])

In [59]:
a=[1,2,3,4.4]
print(a)

[1, 2, 3, 4.4]


In [60]:
type(a[2])

int

In [61]:
x1.dtype

dtype('int32')

In [62]:
print(x1)
x1[0] = 3.14159  # this will be truncated!
print(x1)

[7 6 9 3 6 5]
[3 6 9 3 6 5]


In [63]:
x1[1]='222'

In [64]:
print(x1)

[  3 222   9   3   6   5]


In [65]:
x1[2]='abc'
print(x1)

ValueError: invalid literal for int() with base 10: 'abc'

In [66]:
x2

array([[12,  8,  4,  1],
       [ 3,  6,  5,  3],
       [ 9,  6,  9,  1]])

In [67]:
x2[1,0]

3

In [68]:
print(x2[ 0,:])  # first row of x2

[12  8  4  1]


In [69]:
x2[0]

array([12,  8,  4,  1])

In [70]:
print(x2[:, -1])  # first column of x2

[1 3 1]


In [71]:
x = np.arange(10)
print(x)
print(x[::-1] )  #x[5:]  x[4:7]  x[::2] x[1::2] x[::-1]  

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [72]:

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
print(x[5::-2])

[5 3 1]


# Subarrays as no-copy views

In [73]:
print(x2)

[[12  8  4  1]
 [ 3  6  5  3]
 [ 9  6  9  1]]


In [74]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  8]
 [ 3  6]]


In [75]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  8]
 [ 3  6]]


In [76]:
print(x2)

[[99  8  4  1]
 [ 3  6  5  3]
 [ 9  6  9  1]]


# Creating copies of arrays

In [77]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  8]
 [ 3  6]]


In [78]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  8]
 [ 3  6]]


In [79]:
print(x2)

[[99  8  4  1]
 [ 3  6  5  3]
 [ 9  6  9  1]]


# Reshaping

In [80]:
grid = np.arange(1, 13).reshape(2,6)

print(grid)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [81]:
x = np.array([1, 2, 3])
y=x.reshape((3, 1))
y

array([[1],
       [2],
       [3]])

In [82]:
x

array([1, 2, 3])

# Array Concatenation and Splitting

In [84]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [85]:
a=[1,2,3] 
b=[3,2,1]
a+b

[1, 2, 3, 3, 2, 1]

In [86]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [87]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
grid


array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [89]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [90]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [91]:
np.concatenate([x.reshape(1,3), grid], axis=0)

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [92]:
x.reshape(1,3).ndim

2

In [93]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [94]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [95]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [96]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
upper, lower = np.vsplit(grid, [2])
print('upper:\n',upper)
print('lower:\n',lower)

upper:
 [[0 1 2 3]
 [4 5 6 7]]
lower:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [98]:
left, right = np.hsplit(grid, [1])
print('left:\n',left)
print('right:\n',right)

left:
 [[ 0]
 [ 4]
 [ 8]
 [12]]
right:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


# optimized computation with arrays of data.
vectorized operations, niversal functions

In [99]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [100]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

5.43 s ± 308 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [101]:
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]


In [102]:
%timeit (1.0 / big_array)

6.97 ms ± 337 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [103]:
1.0 / big_array

array([0.1       , 0.01190476, 0.04545455, ..., 0.01428571, 0.01098901,
       0.01149425])

In [104]:
compute_reciprocals(big_array)

array([0.1       , 0.01190476, 0.04545455, ..., 0.01428571, 0.01098901,
       0.01149425])

In [105]:
x = np.arange(9).reshape((3, 3))
print(x)
2 ** x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [106]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [107]:
x+2

array([2, 3, 4, 5])

In [108]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [109]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [111]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x+y


array([5, 7, 9])

# Trigonometric function

In [113]:
theta = np.linspace(0, np.pi, 3)

In [114]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [115]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [116]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]
