# Notes for STATS102, Session 1, Sep 7th, Lecture
partial materials are from the text book 
Python Data Science Handbook: Essential Tools for Working with Data, by Jake VanderPlas, O'Reilly Media; 1 edition (December 10, 2016), ISBN-13: 978-1491912058, full text and code freely available at https://jakevdp.github.io/PythonDataScienceHandbook/.

In [1]:
import pandas
pandas.__version__

'0.22.0'

In [2]:
import numpy as np
import pandas as pd

# The Pandas Series Object

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [6]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[1]

0.5

In [7]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data.index=['b','c','a','d']
data

b    0.25
c    0.50
a    0.75
d    1.00
dtype: float64

In [6]:
data['a']

0.75

In [7]:
data.loc['a']

0.75

In [8]:
data.iloc[0]

0.25

In [9]:
data.values[0]

0.25

In [10]:
data.iloc[0]

0.25

In [11]:
data.loc['a']

0.75

In [12]:
data

b    0.25
c    0.50
a    0.75
d    1.00
dtype: float64

In [13]:
data['c']

0.5

In [14]:
data.loc['c']

0.5

In [15]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [16]:
data.loc[2]

0.25

In [17]:
data.iloc[2]

0.75

In [18]:
data[3]

0.75

In [19]:
data.iloc[3]

1.0

In [21]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [22]:
type(population)

pandas.core.series.Series

In [23]:
population.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [24]:
population_dict['California':'Illinois']

TypeError: unhashable type: 'slice'

In [25]:
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

In [26]:
population['California']

38332521

In [27]:
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

In [28]:
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [29]:
b=population.iloc[0:3]
b

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

In [30]:
population.iloc[0]

38332521

In [31]:
aa=pd.Series([2, 4, 6])
aa

0    2
1    4
2    6
dtype: int64

In [32]:
aa.loc[1]

4

In [33]:
aa.iloc[1]

4

In [34]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [35]:
pd.Series({2:'a', 1:'b', 3:'c'})

1    b
2    a
3    c
dtype: object

In [36]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
#s = pd.Series(sports)
#s['Hockey']
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

In [46]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
a=[np.NaN,1,2,3]
a

[nan, 1, 2, 3]

In [49]:
1.0/a

TypeError: unsupported operand type(s) for /: 'float' and 'list'

In [50]:
max(a)

nan

In [51]:
np.nanmean(a)

2.0

In [52]:
np.mean(a)

nan

# The Pandas DataFrame Object

In [58]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [59]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [60]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [49]:
pd.DataFrame(population,columns=['population'])

population
California    38332521
DKU           12882135
Florida       19552860
New York      19651127
Texas         26448193

In [56]:
states.index

Index(['California', 'DKU', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [57]:
states.columns

Index(['area', 'population'], dtype='object')

In [61]:
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [62]:
states[['area','population']]

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [63]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [64]:
states.loc['California']

area            423967
population    38332521
Name: California, dtype: int64

In [66]:
states.loc['California']['area']

423967

In [67]:
states['area']['California']

423967

In [68]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193

In [69]:
pd.DataFrame(population,columns=['dku'])

dku
California  38332521
Florida     19552860
Illinois    12882135
New York    19651127
Texas       26448193

In [70]:
a=pd.DataFrame(population)
a

0
California  38332521
Florida     19552860
Illinois    12882135
New York    19651127
Texas       26448193

In [71]:
a.columns

RangeIndex(start=0, stop=1, step=1)

In [20]:
a.columns=['somethingelse']
a

somethingelse
California       38332521
DKU              12882135
Florida          19552860
New York         19651127
Texas            26448193

In [72]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [73]:
data1=pd.DataFrame(data)
data1

a  b
0  0  0
1  1  2
2  2  4

In [24]:
data1.loc[1]

a    1
b    2
Name: 1, dtype: int64

In [25]:
pd.DataFrame(data).T

0  1  2
a  0  1  2
b  0  2  4

In [64]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [74]:
pd.DataFrame({'population': population,
              'area': area})

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [75]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.153571  0.962056
b  0.367903  0.096877
c  0.709742  0.538866

# Index as immutable array

In [76]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [77]:
ind[1]=2

TypeError: Index does not support mutable operations

# Index as ordered set

In [84]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [82]:
indA

Int64Index([1, 3, 5, 7, 9], dtype='int64')

In [83]:
indB

Int64Index([2, 5, 3, 7, 11], dtype='int64')

In [85]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [86]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [87]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

# Data Selection in Series

In [88]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'd', 'c', 'b'])
data

a    0.25
d    0.50
c    0.75
b    1.00
dtype: float64

In [89]:
data = pd.Series({'a':0.25,'d':0.50,'c':0.75,'b':1.0})
data

a    0.25
b    1.00
c    0.75
d    0.50
dtype: float64

In [90]:
data['b']

1.0

In [91]:
data['f']

KeyError: 'f'

In [92]:
data

a    0.25
b    1.00
c    0.75
d    0.50
dtype: float64

In [93]:
data.loc['b']

1.0

In [94]:
'c' in data

True

In [95]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [96]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [97]:
list(data.items())

[('a', 0.25), ('b', 1.0), ('c', 0.75), ('d', 0.5)]

In [46]:
data['e'] =1.25
data


a    0.25
b    1.00
c    0.75
d    0.50
e    1.25
dtype: float64

In [47]:
data.loc['a':'c']

a    0.25
b    1.00
c    0.75
dtype: float64

In [48]:
data.iloc[0:2]

a    0.25
b    1.00
dtype: float64

In [49]:
data['a':'c']

a    0.25
b    1.00
c    0.75
dtype: float64

In [90]:
data.iloc[0:2]

a    0.25
b    1.00
dtype: float64

In [98]:
data

a    0.25
b    1.00
c    0.75
d    0.50
dtype: float64

In [99]:
(data > 0.3) & (data < 0.8)

a    False
b    False
c     True
d     True
dtype: bool

In [100]:
(data > 0.3)

a    False
b     True
c     True
d     True
dtype: bool

In [101]:
(data < 0.8)

a     True
b    False
c     True
d     True
dtype: bool

In [102]:
data[(data > 0.3) & (data < 0.8)]

c    0.75
d    0.50
dtype: float64

# Data Selection in DataFrame

In [105]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [106]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [107]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [108]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01]])

In [109]:
data.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [110]:
data.T

California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [111]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [112]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [113]:
data.loc['California':'Illinois']

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [114]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [116]:
data.loc[data['density'] > 100][['pop','area']]

pop    area
Florida   19552860  170312
New York  19651127  141297

In [117]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [118]:
data.iloc[0, 2] = 70
data

area       pop     density
California  423967  38332521   70.000000
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [119]:
data.loc['California','anything']=80
data

area       pop     density  anything
California  423967  38332521   70.000000      80.0
Florida     170312  19552860  114.806121       NaN
Illinois    149995  12882135   85.883763       NaN
New York    141297  19651127  139.076746       NaN
Texas       695662  26448193   38.018740       NaN

In [120]:
data

area       pop     density  anything
California  423967  38332521   70.000000      80.0
Florida     170312  19552860  114.806121       NaN
Illinois    149995  12882135   85.883763       NaN
New York    141297  19651127  139.076746       NaN
Texas       695662  26448193   38.018740       NaN

In [121]:
data.iloc[0]['area']

423967.0

In [122]:
data['area'].iloc[0]

423967

In [123]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [124]:
data.loc['California']

area          423967.0
pop         38332521.0
density           70.0
anything          80.0
Name: California, dtype: float64

In [125]:
data.loc['California'].loc['area']

423967.0

In [126]:
data.loc['California','area']

423967

In [127]:
data['area']>200000

California     True
Florida       False
Illinois      False
New York      False
Texas          True
Name: area, dtype: bool

In [135]:
aa=data.where(data['area']>200000)
b=aa.dropna(how='all')
b
#aa

area         pop   density  anything
California  423967.0  38332521.0  70.00000      80.0
Texas       695662.0  26448193.0  38.01874       NaN

In [132]:
aa.dropna?

In [136]:
aa

area         pop   density  anything
California  423967.0  38332521.0  70.00000      80.0
Florida          NaN         NaN       NaN       NaN
Illinois         NaN         NaN       NaN       NaN
New York         NaN         NaN       NaN       NaN
Texas       695662.0  26448193.0  38.01874       NaN

In [137]:
aa.count()

area        2
pop         2
density     2
anything    1
dtype: int64

In [139]:
aa.count(axis=1)

California    4
Florida       0
Illinois      0
New York      0
Texas         3
dtype: int64

In [138]:
aa.count?

In [115]:
aa['area'].count()

2

In [140]:
data

area       pop     density  anything
California  423967  38332521   70.000000      80.0
Florida     170312  19552860  114.806121       NaN
Illinois    149995  12882135   85.883763       NaN
New York    141297  19651127  139.076746       NaN
Texas       695662  26448193   38.018740       NaN

In [141]:
data.set_index('area')

pop     density  anything
area                                  
423967  38332521   70.000000      80.0
170312  19552860  114.806121       NaN
149995  12882135   85.883763       NaN
141297  19651127  139.076746       NaN
695662  26448193   38.018740       NaN

# while indexing refers to columns, slicing refers to rows:

In [142]:
data['Florida':'Illinois']

area       pop     density  anything
Florida   170312  19552860  114.806121       NaN
Illinois  149995  12882135   85.883763       NaN

In [143]:
data[['area','pop']]

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

# Ufuncs: 

In [144]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'], index=['a','b','c'])
df

A  B  C  D
a  2  9  1  1
b  8  1  6  5
c  9  9  2  9

In [145]:
np.exp2(df)

A      B     C      D
a    4.0  512.0   2.0    2.0
b  256.0    2.0  64.0   32.0
c  512.0  512.0   4.0  512.0

In [146]:
np.sin(df * np.pi / 4)

A         B         C         D
a  1.000000e+00  0.707107  0.707107  0.707107
b -2.449294e-16  0.707107 -1.000000 -0.707107
c  7.071068e-01  0.707107  1.000000  0.707107

In [147]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [148]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [123]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
print(A)
print(B)
print(A + B)

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64
0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64


In [90]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [91]:
B.add(A, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [149]:
A = pd.DataFrame(np.random.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A  B
0  15  7
1  12  8

In [93]:
list('AB')

['A', 'B']

In [94]:
list('ABcd')

['A', 'B', 'c', 'd']

In [95]:
list('DKU')

['D', 'K', 'U']

In [150]:
B = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  1  4  6
1  8  5  5
2  7  6  0

In [151]:
A

A  B
0  15  7
1  12  8

In [98]:
A+B

A    B   C
0  14.0  7.0 NaN
1   8.0  8.0 NaN
2   NaN  NaN NaN

# missing values

In [152]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [153]:
vals1 = np.array([1, None, 3, 4],dtype=int)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [154]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2

array([ 1., nan,  3.,  4.])

In [155]:
type(vals2[0])

numpy.float64

In [156]:
1 + np.nan

nan

In [157]:
0 *  np.nan

nan

In [158]:
vals2.sum(), vals2.min(), vals2.max()

C:\Users\ml442\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
C:\Users\ml442\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)


(nan, nan, nan)

In [159]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [160]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [161]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [162]:
x[0] = np.nan
x

0    NaN
1    1.0
dtype: float64

In [163]:
x

0    NaN
1    1.0
dtype: float64

In [164]:
x.isnull()

0     True
1    False
dtype: bool

In [165]:
np.sum(x.isnull())

1

In [166]:
x.notnull()

0    False
1     True
dtype: bool

In [167]:
x

0    NaN
1    1.0
dtype: float64

In [168]:
x.dropna()

1    1.0
dtype: float64

In [169]:
x.fillna(100)

0    100.0
1      1.0
dtype: float64

In [170]:
x[x.notnull()]

1    1.0
dtype: float64

In [171]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [172]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [173]:
df.dropna(axis='rows')

0    1  2
1  2.0  3.0  5

In [174]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [15]:
df.dropna(axis='columns',how='any')

2
0  2
1  5
2  6

In [175]:
df


0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [176]:
df.fillna(method='bfill')

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6